version: '3.7'

services:
  pyspark:
    build: .
    ports:
      - 8888:8888
      - 4040:4040
    volumes:
      - ./spark_data:/home/user
    entrypoint:
      [
        "jupyter",
        "notebook",
        # "--allow-root",
        "--port=8888",
        "--no-browser",
        "--notebook-dir=/home/user",
        "--ip=0.0.0.0"
      ]
